name: Build and deploy ASP.Net Core and React app to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'
          include-prerelease: true
      - name: Build with dotnet
        run: dotnet build ./backend/BlogPlatformAPI/BlogPlatformAPI.csproj --configuration Release
      - name: dotnet publish
        run: dotnet publish ./backend/BlogPlatformAPI/BlogPlatformAPI.csproj -c Release -o ${{github.workspace}}/published_app

  build-frontend:
    runs-on: ubuntu-latest
    needs: build-backend

    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '21.7.1' 
      - name: Install npm dependencies
        run: npm install
        working-directory: ./frontend/ReactTSBlogPlatform
      - name: Build frontend project
        run: npm run build
        working-directory: ./frontend/ReactTSBlogPlatform
      - name: Upload frontend build as artifact
        uses: actions/upload-artifact@v3
        with:
          name: frontend-build
          path: ${{github.workspace}}/frontend/ReactTSBlogPlatform/dist

  deploy:
    runs-on: ubuntu-latest
    needs: [build-backend, build-frontend]
    environment:
      name: 'Production'

    steps:
      - name: Download backend artifact
        uses: actions/download-artifact@v3
        with:
          name: published_app
      - name: Download frontend artifact
        uses: actions/download-artifact@v3
        with:
          name: frontend-build
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'blogplatform'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: published_app
